apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  labels:
    cnpg.io/cluster: authentik
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: freenas-iscsi
  managed:
    roles:
      - name: authentik
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: authentik-database-credentials
