---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: Authentik-FSN1
        property: secret_key
    - secretKey: psql_password
      remoteRef:
        key: Authentik-FSN1
        property: psql_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-database-credentials
spec:
  target:
    name: authentik-database-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        name: authentik
        password: "{{ .psql_password }}"
  data:
    - secretKey: psql_password
      remoteRef:
        key: Authentik-FSN1
        property: psql_password