---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  interval: 30m
  chart:
    spec:
      chart: gatekeeper
      version: v3.20.1
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      interval: 30m
